package multitenant.url

import groovy.sql.Sql

import javax.sql.DataSource

class BootStrap {

    DataSource dataSource
    TenantValidatorService tenantValidatorService

    def init = { servletContext ->
        Sql sql = new Sql(dataSource)
        // create schemas first - for development I've got them at the end of the H2 url ;INIT=CREATE SCHEMA IF NOT EXISTS prefix1\;
        tenantValidatorService.buildValidTenants(dataSource)

        tenantValidatorService.tenants.each { tenant->
            tenantValidatorService.setSchema(dataSource, tenant)
            // from turning on logSql and setting dbCreate: create
            sql.execute('create table Test (id bigint generated by default as identity, version bigint not null, name varchar(20) not null, primary key (id))')
            sql.execute('alter table Test add constraint UK_ex465bpneon54qrrtfakuwi79 unique (name)')
        }
    }
    def destroy = {
    }
}
